export const DOCUMENT_SSRM_SETTINGS = [
	{
		key: 'system_id',
		name: 'Reference ID',
		visible: true,
		type: 'text',
		isFilterable: true,
		isSortable: true,
		filterType: 'text',
		priority: 0,
	},
	{
		key: 'buyer_details.name',
		name: 'Customer Name',
		visible: true,
		type: 'text',
		isFilterable: true,
		isSortable: true,
		filterType: 'text',
		priority: 1,
	},
	{
		key: 'document_status',
		name: 'Status',
		visible: true,
		type: 'status',
		isFilterable: false,
		isSortable: true,
		filterType: 'set',
		priority: 2,
	},
	{ filterType: 'set', isFilterable: true, isSortable: true, key: 'type', name: 'Type', type: 'tags', visible: true, priority: 3 },
	{
		key: 'payment_status',
		name: 'Payment Status',
		visible: false,
		type: 'select',
		isFilterable: true,
		isSortable: true,
		filterType: 'set',
		filter: 'agSetColumnFilter',
		filterParams: { maxNumConditions: 1, values: ['PAID', 'PENDING', 'PARTIALLY_REFUNDED', 'REFUNDED', 'VOIDED', 'OVERPAID'] },
		priority: 4,
	},
	{
		key: 'fulfillment_status',
		name: 'Fulfilment Status',
		visible: true,
		type: 'select',
		isFilterable: true,
		isSortable: true,
		filterType: 'set',
		filter: 'agSetColumnFilter',
		filterParams: {
			maxNumConditions: 1,
			values: [
				'DELIVERED',
				'UNFULFILLED',
				'FULFILLED',
				'TRACKING_INFO_ADDED',
				'IN_TRANSIT',
				'OUT_FOR_DELIVERY',
				'PARTIALLY_DELIVERED',
				'PARTIALLY_FULFILLED',
			],
		},
		priority: 5,
	},
	{
		key: 'user_details.name',
		name: 'Sales rep',
		visible: true,
		type: 'text',
		isFilterable: false,
		isSortable: true,
		filterType: 'set',
		priority: 6,
	},
	{
		key: 'total_value',
		name: 'Order value',
		visible: true,
		type: 'range',
		isFilterable: false,
		isSortable: true,
		filterType: 'number',
		priority: 8,
	},
	{
		key: 'updated_at',
		name: 'Last Updated at',
		visible: true,
		type: 'unixdate',
		isFilterable: false,
		isSortable: true,
		filterType: 'date',
		priority: 9,
	},
	{
		key: 'created_at',
		name: 'Created On',
		visible: false,
		type: 'unixdate',
		isFilterable: false,
		isSortable: true,
		filterType: 'date',
		priority: 10,
	},
];
