export const QUOTE_SETTINGS = {
	sections: [
		{
			key: 'buyer_details',
			name: 'Customer Details',
			priority: 0,
			attributes: [
				{
					id: 'primary_contact',
					name: 'Customer Details',
					type: 'primary_contact',
					value: '',
					priority: 0,
					required: true,
					reference_id: '',
					is_quote_mandatory: true,
					is_quote_display: false,
				},
			],
			required: true,
			is_display: true,
			is_quote_mandatory: true,
			is_quote_display: true,
			is_mandatory: true,
		},
		{
			key: 'send_emails_to',
			name: 'Send emails to',
			priority: 1,
			attributes: [
				{
					id: 'notification_email_ids',
					name: 'Emails',
					type: 'notification_emails',
					value: '',
					priority: 0,
					required: false,
					is_quote_mandatory: false,
					is_quote_display: false,
				},
			],
			required: true,
			is_display: true,
			is_quote_mandatory: true,
			is_quote_display: true,
			is_mandatory: true,
		},
		{
			key: 'billing_address',
			name: 'Billing Address',
			priority: 0,
			attributes: [
				{
					id: 'billing_address',
					name: 'Billing Address',
					type: 'address',
					value: '',
					priority: 0,
					required: true,
					reference_id: '',
					is_quote_mandatory: true,
					is_quote_display: false,
				},
			],
			is_quote_mandatory: true,
			is_quote_display: true,
			is_display: true,
			required: true,
			is_mandatory: true,
		},
		{
			key: 'shipping_address',
			name: 'Shipping Address',
			priority: 0,
			attributes: [
				{
					id: 'shipping_address',
					name: 'Shipping Address',
					type: 'address',
					value: '',
					priority: 0,
					required: true,
					reference_id: '',
					is_quote_mandatory: true,
					is_quote_display: false,
				},
			],
			is_quote_mandatory: true,
			is_quote_display: true,
			is_display: true,
			is_mandatory: true,
		},
		{
			key: 'order_details',
			name: 'Order Details',
			priority: 0,
			attributes: [],
			is_display: true,
			is_quote_display: true,
		},
		{
			attributes: [
				{
					id: 'notes_settings',
					name: 'Notes settings',
					priority: 0,
					required: false,
					type: 'notes_settings',
				},
			],
			key: 'notes',
			name: 'Notes',
			priority: 4,
			is_display: true,
			is_mandatory: false,
			is_quote_display: true,
			is_quote_mandatory: false,
		},
		{
			name: 'Payment Method',
			priority: 4,
			key: 'payment_method',
			is_display: true,
			is_quote_display: true,
			attributes: [
				{
					id: 'payment_method',
					name: 'Payment Method',
					type: 'select',
					options: [
						{
							label: 'Wire Transfer',
							value: 'wiretransfer',
						},
						{
							label: 'Debit Card',
							value: 'debitcard',
						},
						{
							label: 'Credit Card',
							value: 'creditcard',
						},
						{
							label: 'Cash',
							value: 'cash',
						},
					],
					priority: 0,
					required: false,
					is_quote_mandatory: false,
					is_quote_display: true,
					value: '',
					is_display: true,
				},
			],
		},
		{
			attributes: [
				{
					id: 'shipping_method',
					name: 'Shipment Method',
					options: [
						{
							label: 'FedEx',
							value: 'fedex',
						},
						{
							label: 'UPS',
							value: 'ups',
						},
						{
							label: 'USPS',
							value: 'usps',
						},
						{
							label: 'DHL',
							value: 'dhl',
						},
						{
							label: 'Estes',
							value: 'estes',
						},
					],
					priority: 0,
					required: false,
					type: 'select',
					is_quote_mandatory: false,
					is_quote_display: false,
				},
			],
			name: 'Shipping Method',
			key: 'shipping_method',
			priority: 3,
		},
		{
			key: 'freight_terms',
			is_display: true,
			name: 'Freight Term',
			priority: 5,
			attributes: [
				{
					id: 'freight_terms',
					name: 'Freight Terms',
					options: [
						{
							label: 'FEDEX ACCOUNT# 658399233',
							value: 'fedex_account#_658399233',
						},
						{
							label: '***UPS 3RD PARTY 670455',
							value: '***ups_3rd_party_670455',
						},
						{
							label: '**99 FFA**',
							value: '**99_ffa**',
						},
						{
							label: '**100 FFA**',
							value: '**100_ffa**',
						},
						{
							label: '*SHIP UPS 3RD PARTY #3057E5 UNDER $500*',
							value: '*ship_ups_3rd_party_#3057e5_under_$500*',
						},
						{
							label: '**FFA***',
							value: '**ffa***',
						},
						{
							label: '****UPS ACCT 69Y65A****',
							value: '****ups_acct_69y65a****',
						},
						{
							label: '*PLEASE USE FEDEX LABEL PROVIDED*',
							value: '*please_use_fedex_label_provided*',
						},
						{
							label: '**FEDEX 3RD PARTY 3486-7292-4',
							value: '**fedex_3rd_party_3486-7292-4',
						},
						{
							label: '**UPS 3RD PARTY 23A79F*',
							value: '**ups_3rd_party_23a79f*',
						},
						{
							label: '**FEDEX 3RD PARTY # 214586223**',
							value: '**fedex_3rd_party_#_214586223**',
						},
						{
							label: '*UPS 3RD PARTY**',
							value: '*ups_3rd_party**',
						},
						{
							label: '***FFA $99***',
							value: '***ffa_$99***',
						},
						{
							label: 'FFA ALL- US PRICING',
							value: 'ffa_all-_us_pricing',
						},
						{
							label: '**UPS 3RD PARTY W4E170**NO DROP SHIP FEE',
							value: '**ups_3rd_party_w4e170**no_drop_ship_fee',
						},
						{
							label: '***UPS 019RE4***',
							value: '***ups_019re4***',
						},
						{
							label: '*FFA  ALL*',
							value: '*ffa__all*',
						},
						{
							label: 'US Standard - Lighting 1',
							value: 'us_standard_-_lighting_1',
						},
						{
							label: 'FFA/100',
							value: 'ffa/100',
						},
						{
							label: '**FFA  ALL ORDERS**',
							value: '**ffa__all_orders**',
						},
						{
							label: '** SHIP UPS   3Y319W** ORDERS UND $500',
							value: '**_ship_ups___3y319w**_orders_und_$500',
						},
						{
							label: '**ship using their account**',
							value: '**ship_using_their_account**',
						},
						{
							label: '**FFA OVER 100**',
							value: '**ffa_over_100**',
						},
						{
							label: '**FEDEX 3RD PARTY # 876058081**',
							value: '**fedex_3rd_party_#_876058081**',
						},
						{
							label: '**FFA 100**',
							value: '**ffa_100**',
						},
						{
							label: '*NO DROP SHIP FEE****FEDEX ACCT # 620409995***',
							value: '*no_drop_ship_fee****fedex_acct_#_620409995***',
						},
						{
							label: 'US Standard No Fees - Lighting 1',
							value: 'us_standard_no_fees_-_lighting_1',
						},
						{
							label: '**99  FFA**',
							value: '**99__ffa**',
						},
						{
							label: '**UPS 3RD PARTY 946586*',
							value: '**ups_3rd_party_946586*',
						},
						{
							label: '***SHIP UPS ACCOUNT # 6Y4915***',
							value: '***ship_ups_account_#_6y4915***',
						},
						{
							label: 'UPS 3RD  PARTY ACCOUNT# T3301T',
							value: 'ups_3rd__party_account#_t3301t',
						},
						{
							label: 'Canada Standard',
							value: 'canada_standard',
						},
						{
							label: '***FFA ON ALL***',
							value: '***ffa_on_all***',
						},
						{
							label: '**UPS 3RD PARTY 4F4030**',
							value: '**ups_3rd_party_4f4030**',
						},
						{
							label: '**FFA/TUESDAY**UPS 3RD PARTY#6A7E32*',
							value: '**ffa/tuesday**ups_3rd_party#6a7e32*',
						},
						{
							label: '**FFA 99 EVERYDAY**',
							value: '**ffa_99_everyday**',
						},
						{
							label: '***FFA***',
							value: '***ffa***',
						},
						{
							label: '**SHIP UPS E1R828**',
							value: '**ship_ups_e1r828**',
						},
						{
							label: '**UPS 3RD PARTY 866Y1W**',
							value: '**ups_3rd_party_866y1w**',
						},
						{
							label: 'US Standard',
							value: 'us_standard',
						},
						{
							label: '*FFA*',
							value: '*ffa*',
						},
						{
							label: '***99 FFA***',
							value: '***99_ffa***',
						},
						{
							label: '**ups acct 48X232*******  99 FFA',
							value: '**ups_acct_48x232*******__99_ffa',
						},
						{
							label: '***third party billing************',
							value: '***third_party_billing************',
						},
						{
							label: '**FFA ALL ************',
							value: '**ffa_all_************',
						},
						{
							label: '*FEDEX 3RD PARTY ACCOUNT#251150427',
							value: '*fedex_3rd_party_account#251150427',
						},
						{
							label: '***FFA OVER 100***',
							value: '***ffa_over_100***',
						},
						{
							label: '***FFA+100**',
							value: '***ffa+100**',
						},
						{
							label: '*******USE UPS A952Y1*******',
							value: '*******use_ups_a952y1*******',
						},
						{
							label: '***FFA/100***',
							value: '***ffa/100***',
						},
						{
							label: '**UPS 3RD PARTY E6Y320**',
							value: '**ups_3rd_party_e6y320**',
						},
						{
							label: '*UPS 3RD PARTY ACCT # 8313V2*',
							value: '*ups_3rd_party_acct_#_8313v2*',
						},
						{
							label: 'US Standard No Fees',
							value: 'us_standard_no_fees',
						},
						{
							label: '***FEDEX 3RD PARTY ACCOUNT***',
							value: '***fedex_3rd_party_account***',
						},
						{
							label: 'THIRD PARTY',
							value: 'third_party',
						},
						{
							label: 'FEDEX 3RD PARTY 149085114**',
							value: 'fedex_3rd_party_149085114**',
						},
						{
							label: 'FFA',
							value: 'ffa',
						},
						{
							label: '***PLEASE USE UPS ACCT #535024***',
							value: '***please_use_ups_acct_#535024***',
						},
						{
							label: '99 FFA',
							value: '99_ffa',
						},
					],
					priority: 10,
					required: false,
					type: 'select',
					is_quote_mandatory: false,
					is_quote_display: true,
					value: '',
					is_display: true,
				},
			],
			is_quote_display: true,
		},
		{
			name: 'Payment Terms',
			priority: 10,
			is_display: true,
			key: 'payment_terms',
			attributes: [
				{
					id: 'payment_terms',
					is_display: true,
					name: 'Payment terms',
					options: [
						{
							label: 'PIA',
							value: 'pia',
						},
						{
							label: 'Net 7',
							value: 'net7',
						},
						{
							label: 'Net 10',
							value: 'net10',
						},
						{
							label: 'Net 30',
							value: 'net30',
						},
						{
							label: 'Net 60',
							value: 'net60',
						},
						{
							label: 'Net 90',
							value: 'net90',
						},
						{
							label: 'Due on Receipt',
							value: 'due_on_receipt',
						},
					],
					priority: 0,
					required: false,
					type: 'select',
					is_quote_mandatory: false,
					is_quote_display: true,
					value: '',
				},
			],
			is_quote_display: true,
		},
		{
			attributes: [
				{
					id: 'payment_method_v2',
					name: 'Payment Method',
					priority: 0,
					reference_id: '',
					required: false,
					type: '',
					value: '',
					disabled: false,
					back_saving_permitted: false,
					is_display: false,
					is_quote_mandatory: false,
					is_quote_display: false,
				},
			],
			key: 'payment_method_v2',
			name: 'Payment Method',
			priority: 0,
			is_display: false,
			is_mandatory: false,
			is_quote_mandatory: false,
			is_quote_display: false,
		},
		{
			key: 'customer_consent',
			name: 'Customer consent',
			priority: 10,
			attributes: [
				{
					id: 'customer_consent',
					name: 'All above information is updated post discussion with the customer',
					type: 'checkbox',
					label: 'This field is required',
					value: false,
					priority: 0,
					required: false,
					disabled: false,
					back_saving_permitted: false,
					is_quote_mandatory: false,
					is_quote_display: false,
					is_display: false,
					attribute_class: null,
					dynamic_attr_config: null,
					edit_permitted: false,
					add_permitted: false,
				},
				{
					id: 'signature',
					name: 'signature',
					type: 'signature',
					value: '',
					priority: 2,
					required: false,
					disabled: false,
					back_saving_permitted: false,
					is_display: false,
					is_quote_mandatory: false,
					is_quote_display: false,
					attribute_class: null,
					dynamic_attr_config: null,
					edit_permitted: false,
					add_permitted: false,
				},
			],
			required: false,
			is_display: false,
			is_quote_mandatory: false,
			is_quote_display: false,
			is_mandatory: false,
		},
		{
			key: 'sales_rep_details',
			name: 'Salesrep Details',
			priority: 0,
			is_quote_mandatory: false,
			is_quote_display: false,
			is_display: false,
			disabled: false,
			attributes: [
				{
					id: 'written_for',
					name: 'Written for',
					type: 'select',
					options: [],
					value: '',
					priority: 0,
					required: false,
					disabled: false,
					reference_id: '',
					is_display: false,
					is_quote_mandatory: false,
					is_quote_display: false,
					attribute_class: null,
					dynamic_attr_config: null,
					is_label_display: false,
					is_display_exclusion_type: ['billing', 'shipping'],
					required_exclusion_type: ['billing', 'shipping'],
				},
				{
					id: 'written_by',
					name: 'Written by',
					type: 'select',
					options: [],
					value: '',
					priority: 0,
					required: false,
					disabled: false,
					reference_id: '',
					is_display: false,
					is_quote_mandatory: false,
					is_quote_display: false,
				},
			],
			is_mandatory: false,
		},
	],
	tags: [],
};
