export const columns = [
	{
		headerName: 'Name',
		field: 'name',
		headerStyle: {},
		cellStyle: {},
		visibility: true,
		dtype: 'text',
		filterValues: [],
		editable: false,
		width: 350,
		flex: 1,
		lockPosition: true,
		menuTabs: [],
	},
	{
		headerName: 'Applicable On',
		field: 'applicableOn',
		headerStyle: {},
		cellStyle: {},
		visibility: true,
		dtype: 'text',
		filterValues: [],
		editable: false,
		width: 300,
		flex: 1,
		menuTabs: [],
	},
	{
		headerName: 'Price List',
		field: 'priceList',
		headerStyle: {},
		cellStyle: {},
		visibility: true,
		dtype: 'text',
		filterValues: [],
		editable: false,
		width: 350,
		flex: 1,
		menuTabs: [],
	},
	{
		headerName: 'Created On',
		field: 'createdOn',
		headerStyle: {},
		cellStyle: {},
		visibility: true,
		dtype: 'text',
		filterValues: [],
		editable: false,
		width: 350,
		flex: 1,
		menuTabs: [],
	},
];

export const buyerColumns = [
	{
		headerName: 'Customer Name',
		field: 'buyerName',
		headerStyle: {},
		cellStyle: {},
		visibility: true,
		dtype: 'text',
		editable: false,
		minWidth: 250,
		flex: 1,
	},
	{
		headerName: 'Region',
		field: 'region',
		headerStyle: {},
		cellStyle: {},
		visibility: true,
		dtype: 'text',
		editable: false,
		minWidth: 250,
		flex: 1,
	},
	{
		headerName: 'Total Revenue',
		field: 'totalRevenue',
		headerStyle: {},
		cellStyle: {},
		visibility: true,
		dtype: 'text',
		editable: false,
		minWidth: 250,
		flex: 1,
	},
];
