export const content_type_to_extension: any = {
	'application/pdf': 'pdf',
	'application/x-iwork-pages-sffpages': 'pages',
	'image/jpeg': 'jpeg',
	'image/png': 'png',
	'image/gif': 'gif',
	'video/mp4': 'mp4',
	'video/webm': 'webm',
	'video/x-msvideo': 'avi',
	'audio/wav': 'wav',
	'audio/mpeg': 'mp3',
	'text/plain': 'txt',
	'text/html': 'html',
	'application/json': 'json',
	'application/xml': 'xml',
	'application/zip': 'zip',
	'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'docx',
	'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'xlsx',
	'application/vnd.openxmlformats-officedocument.presentationml.presentation': 'pptx',
	null: '',
};
