export const columns = [
	{
		headerName: 'Customer Name',
		field: 'buyerName',
		headerStyle: {},
		cellStyle: {},
		visibility: true,
		dtype: 'text',
		filterValues: [],
		editable: false,
		flex: 1,
		minWidth: 200,
		suppressSizeToFit: true,
		autoSize: true,
	},
	{
		headerName: 'Region',
		field: 'region',
		headerStyle: {},
		cellStyle: {},
		visibility: true,
		dtype: 'text',
		filterValues: [],
		editable: false,
		flex: 1,
		minWidth: 200,
		suppressSizeToFit: true,
		autoSize: true,
	},
	{
		headerName: 'Orders',
		field: 'orders',
		headerStyle: {},
		cellStyle: {},
		visibility: true,
		dtype: 'number',
		filterValues: [],
		editable: false,
		flex: 1,
		minWidth: 200,
		suppressSizeToFit: true,
		autoSize: true,
	},
	{
		headerName: 'Drafts',
		field: 'drafts',
		headerStyle: {},
		cellStyle: {},
		visibility: true,
		dtype: 'number',
		filterValues: [],
		editable: false,
		flex: 1,
		minWidth: 200,
		suppressSizeToFit: true,
		autoSize: true,
	},
	{
		headerName: 'Open Carts',
		field: 'openCarts',
		headerStyle: {},
		cellStyle: {},
		visibility: true,
		dtype: 'number',
		filterValues: [],
		editable: false,
		flex: 1,
		minWidth: 200,
		suppressSizeToFit: true,
		autoSize: true,
	},
	{
		headerName: 'Sales Rep',
		field: 'salesRep',
		headerStyle: {},
		cellStyle: {},
		visibility: true,
		dtype: 'text',
		filterValues: [],
		editable: false,
		flex: 1,
		minWidth: 200,
		suppressSizeToFit: true,
		autoSize: true,
	},
	{
		headerName: 'Customer Group',
		field: 'buyerGroup',
		headerStyle: {},
		cellStyle: {},
		visibility: true,
		dtype: 'text',
		filterValues: [],
		editable: false,
		flex: 1,
		minWidth: 200,
		suppressSizeToFit: true,
		autoSize: true,
	},
];

export const rowData = [
	{
		buyerName: 'John Doe',
		region: 'North America',
		orders: 120,
		drafts: 30,
		openCarts: 2,
		salesRep: 'Sarah Smith',
		buyerGroup: 'Group A',
	},
	{
		buyerName: 'Jane Smith',
		region: 'Europe',
		orders: 200,
		drafts: 50,
		openCarts: 1,
		salesRep: 'John Brown',
		buyerGroup: 'Group B',
	},
	{
		buyerName: 'Bill Johnson',
		region: 'Asia',
		orders: 150,
		drafts: 40,
		openCarts: 3,
		salesRep: 'Emily Taylor',
		buyerGroup: 'Group C',
	},
	{
		buyerName: 'Mary Davis',
		region: 'South America',
		orders: 180,
		drafts: 60,
		openCarts: 4,
		salesRep: 'William Jones',
		buyerGroup: 'Group D',
	},
	{
		buyerName: 'James Wilson',
		region: 'Africa',
		orders: 210,
		drafts: 70,
		openCarts: 2,
		salesRep: 'Elizabeth Moore',
		buyerGroup: 'Group E',
	},
];

export const attributes = [
	{
		name: 'First Name',
		id: 'first_name',
		priority: 0,
		required: true,
		type: 'text',
		value: '',
	},
	{
		name: 'Last Name',
		id: 'last_name',
		priority: 1,
		required: false,
		type: 'text',
		value: '',
	},
	{
		name: 'Email',
		id: 'email',
		priority: 2,
		required: true,
		type: 'email',
		value: '',
	},
	{
		name: 'Phone number',
		id: 'phone',
		priority: 3,
		required: false,
		type: 'phone',
		value: '',
	},
];

export const checkbox_attribute = {
	name: 'Send invite on email',
	id: 'send_invite',
	priority: 3,
	type: 'checkbox',
	value: false,
};
