import { makeStyles } from '@mui/styles';
import { colors } from 'src/utils/theme';

const useStyles = makeStyles((theme: any) => ({
	container: {
		background: theme?.payments?.white,
		borderRadius: 12,
		padding: '16px',
	},
	radio_button_container: {
		display: 'flex',
		alignItems: 'flex-start',
		alignContent: 'flex-start',
		gap: '12px',
		alignSelf: 'stretch',
		flexWrap: 'wrap',
		position: 'sticky',
		top: 0,
		zIndex: 10,
		backgroundColor: theme?.payments?.grey_400,
		paddingBottom: '16px',
	},
	active_radio_button: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		border: `1px solid ${theme.payments?.green}`,
		background: theme?.payments?.white,
		padding: '0px 8px 0px 0px',
		borderRadius: '12px',
		cursor: 'pointer',
	},
	radio_button: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		background: theme?.payments?.white,
		padding: '0px 8px 0px 0px',
		border: `1px solid ${theme?.payments?.transparent}`,
		borderRadius: '12px',
		cursor: 'pointer',
	},
	customer_details_section: {
		backgroundColor: theme?.payments?.background,
		padding: '12px',
		borderRadius: 12,
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
	},
	avatar: {
		backgroundColor: theme?.payments?.light_yellow,
		color: theme?.payments?.accent_yellow,
		padding: '25px',
		border: `1.6px solid ${theme?.payments?.white}`,
	},
	icon_style: {
		width: 20,
		height: 20,
		cursor: 'pointer',
		color: theme?.payments?.grey_600,
	},
	total_card: {
		borderRadius: '8px',
		padding: '6px 8px',
		display: 'flex',
		justifyContent: 'space-between',
		backgroundColor: theme?.payments.light_green,
		marginTop: '24px',
	},
	payment_footer_section: {
		position: 'fixed',
		bottom: 0,
		left: 35,
		width: '100%',
		background: theme?.payments?.white,
		padding: '12px',
		display: 'flex',
		justifyContent: 'center',
		zIndex: 100,
		borderTop: '1px solid rgba(0, 0, 0, 0.12)',
	},
	payment_footer_container: {
		display: 'flex',
		flexDirection: 'column',
		width: '100%',
	},
	use_credits: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: '12px 16px',
		background: theme?.payments?.light_blue,
		borderRadius: '12px',
		width: '100%',
	},
	footer_action: {
		display: 'flex',
		alignItems: 'center',
		width: '100%',
	},
	total_charge: {
		display: 'flex',
		justifyContent: 'space-between',
		borderRadius: '12px',
		background: theme?.payments?.green_100,
		padding: '12px 16px',
	},
	invoice_item: {
		borderRadius: '12px',
		padding: '12px',
	},
	payment_order_details: {
		padding: '16px',
		borderRadius: '12px',
		background: theme?.payments?.background,
	},
	add_new_card: {
		cursor: 'pointer',
	},
	refund_form_container: {
		borderRadius: '24px',
		background: colors.white,
		width: '100%',
		padding: '16px',
		display: 'flex',
		flexDirection: 'column',
		gap: '16px',
	},
	transaction_item: {
		background: colors.white,
	},
	transaction_details: {
		width: '100%',
		background: colors.grey_600,
		padding: '12px 16px',
		borderRadius: '8px',
	},
	total_refunded: {
		display: 'flex',
		justifyContent: 'space-between',
		paddingTop: '1rem',
	},
	card_style: {
		width: '100%',
		height: '164px',
		margin: '10px',
		padding: '8px',
		boxShadow: 'none',
	},
	refund_wallet: {
		background: theme?.payments?.grey_light,
		borderRadius: '12px',
		padding: '12px 16px',
	},
	refund_list: {
		background: theme?.payments?.grey_light,
		borderRadius: '12px',
		padding: '12px 16px',
		display: 'flex',
		justifyContent: 'space-between',
	},
	ach_banner: {
		display: 'flex',
		padding: '8px',
		gap: '10px',
		backgroundColor: theme?.payments?.light_green,
		borderRadius: '12px',
	},
	payable_amount_section: {
		padding: '8px 12px 16px 12px',
		borderRadius: '12px',
		background: '#F7F8FA',
	},
	date_section: {
		display: 'flex',
		flexDirection: 'row',
		gap: '16px',
	},
	total_amount: {
		background: '#FCEFD6',
		borderRadius: '8px',
		padding: '8px 12px',
	},
	frequency_section: {
		margin: '16px 0px',
	},
	empty_select_state: {
		height: '50px',
		border: `1px solid ${theme?.payments?.grey_300}`,
		borderRadius: '8px',
		width: '100%',
	},
	recurring_amount: {
		display: 'flex',
		background: '#F7F8FA',
		padding: '12px 16px',
		borderRadius: '8px',
		justifyContent: 'space-between',
		alignItems: 'center',
	},
	scheduled_header: {
		display: 'flex',
		background: '#F0F6FF',
		padding: '12px 16px',
		borderRadius: '8px',
		justifyContent: 'space-between',
	},
}));

export default useStyles;
