export const wizshop_rows = [
	{
		headerName: 'Name',
		field: 'name',
		editable: true,
		width: 240,
		dtype: 'text',
		type: 'text',
		hideFilter: true,
	},
	{
		headerName: 'Email',
		field: 'email',
		editable: true,
		width: 250,
		dtype: 'text',
		type: 'text',
		hideFilter: true,
	},
	{
		headerName: 'Phone',
		field: 'phone',
		editable: true,
		width: 250,
		dtype: 'text',
		type: 'text',
		hideFilter: true,
	},
	{
		headerName: 'Status',
		field: 'status',
		editable: true,
		width: 240,
		dtype: 'text',
		type: 'text',
		hideFilter: true,
	},
	{
		headerName: '',
		field: 'menu',
		editable: false,
		width: 110,
		maxWidth: 110,
		dtype: 'icon',
		type: 'icon',
		cellRenderer: 'menuCellRenderer',
		cellRendererParams: {
			handle_open_drawer: null,
			handle_delete: null,
		},
		hideFilter: true,
		pinned: 'right',
	},
];
