export const PDP = [
	{
		key: 'custom_attributes',
		title: 'Customize Product Attributes',
		subtitle: '',
		config: [
			{
				suppressMenu: true,
				headerName: 'Attribute name',
				field: 'name',
				dtype: 'text',
				flex: 1,
				editable: false,
				hideFilter: true,
				minWidth: 200,
			},
			{
				suppressMenu: true,
				headerName: 'Type',
				field: 'data_type',
				dtype: 'text',
				flex: 1,
				editable: false,
				hideFilter: true,
				minWidth: 200,
			},
		],
		actions: [
			{
				name: 'Edit',
				action: 'edit',
				icon: 'IconEdit',
				key: 'edit',
			},
			{
				name: 'Delete',
				action: 'delete',
				icon: 'IconTrash',
				key: 'delete',
			},
		],
		rowData: [],
		action_button: {
			key: 'attribute',
			title: '+ Add custom attribute',
		},
	},
	{
		key: 'sections',
		title: 'Customize display sections',
		subtitle: 'Select the attributes you wish to display within each section and also decide their order',
		config: [
			{
				suppressMenu: true,
				rowDrag: (params: any) => params?.node?.data?.key !== 'basic_details',
				width: 50,
				minWidth: 50,
				headerName: '',
				cellStyle: { width: '50px' },
			},
			{
				suppressMenu: true,
				headerName: 'Section name',
				field: 'name',
				dtype: 'text',
				flex: 1,
				editable: false,
				hideFilter: true,
				minWidth: 200,
			},
			{
				suppressMenu: true,
				headerName: 'Attributes',
				field: 'attributes',
				dtype: 'multiselect',
				flex: 1,
				editable: false,
				hideFilter: true,
				minWidth: 200,
			},
		],
		actions: [
			{
				name: 'Edit',
				action: 'edit',
				icon: 'IconEdit',
				key: 'edit',
			},
			{
				name: 'Delete',
				action: 'delete',
				icon: 'IconTrash',
				key: 'delete',
			},
		],
		rowData: [],
		action_button: {
			key: 'section',
			title: '+ Add custom section',
		},
	},
	{
		key: 'rails',
		title: 'Rails',
		subtitle: 'Select the rails that you wish to be displayed on your product details page',
		config: [
			{ suppressMenu: true, rowDrag: true, width: 50, minWidth: 50, headerName: '', cellStyle: { width: '50px' } },
			{
				suppressMenu: true,
				headerName: 'Rail name',
				field: 'name',
				dtype: 'text',
				flex: 1,
				editable: false,
				hideFilter: true,
				minWidth: 200,
			},
			{
				suppressMenu: true,
				headerName: 'Alias',
				field: 'type',
				dtype: 'text',
				flex: 1,
				editable: false,
				hideFilter: true,
				minWidth: 200,
			},
			{
				suppressMenu: true,
				headerName: 'Active',
				field: 'is_active',
				flex: 1,
				editable: false,
				disable: true,
				dtype: 'toggle',
				hideFilter: true,
				minWidth: 200,
			},
		],
		actions: [
			{
				name: 'Edit',
				action: 'edit',
				icon: 'IconEdit',
				key: 'edit',
			},
		],
		rowData: [
			{ rail_name: 'Similar products', alias: 'Similar', is_active: false },
			{ rail_name: 'Frequently bought together', alias: 'FBT', is_active: true },
		],
	},
];

export const PLP_RAILS = [
	{
		key: 'rails',
		title: 'Rails',
		subtitle: 'Select the rails that you wish to be displayed on your product details page',
		config: [
			{ suppressMenu: true, rowDrag: true, width: 50, minWidth: 50, headerName: '', cellStyle: { width: '50px' } },
			{
				suppressMenu: true,
				headerName: 'Rail name',
				field: 'name',
				dtype: 'text',
				flex: 1,
				editable: false,
				hideFilter: true,
				minWidth: 200,
			},
			{
				suppressMenu: true,
				headerName: 'Alias',
				field: 'type',
				dtype: 'text',
				flex: 1,
				editable: false,
				hideFilter: true,
				minWidth: 200,
			},
			{
				suppressMenu: true,
				headerName: 'Active',
				field: 'is_active',
				flex: 1,
				editable: false,
				disable: true,
				dtype: 'toggle',
				hideFilter: true,
				minWidth: 200,
			},
		],
		actions: [
			{
				name: 'Edit',
				action: 'edit',
				icon: 'IconEdit',
				key: 'edit',
			},
		],
		rowData: [
			{ rail_name: 'Similar products', alias: 'Similar', is_active: false },
			{ rail_name: 'Frequently bought together', alias: 'FBT', is_active: true },
		],
	},
];
export const PLP = {
	config: [
		{ suppressMenu: true, rowDrag: true, width: 50, minWidth: 50, headerName: '', cellStyle: { width: '50px' } },
		{
			suppressMenu: true,
			headerName: 'Search tags',
			field: 'short_label',
			dtype: 'text',
			flex: 1,
			editable: false,
			hideFilter: true,
			minWidth: 200,
		},
		{
			suppressMenu: true,
			headerName: 'Active',
			field: 'is_active',
			cellRenderer: 'agCheckboxCellRenderer',
			cellEditor: 'agCheckboxCellEditor',
			flex: 1,
			editable: false,
			disable: true,
			hideFilter: true,
			minWidth: 200,
		},
		{
			suppressMenu: true,
			headerName: 'Default',
			field: 'is_default',
			cellRenderer: 'agCheckboxCellRenderer',
			cellEditor: 'agCheckboxCellEditor',
			flex: 1,
			editable: false,
			disable: true,
			hideFilter: true,
			minWidth: 200,
		},
	],
	actions: [
		{
			name: 'Edit',
			action: 'edit',
			icon: 'IconEdit',
			key: 'edit',
		},
	],
};
