/* eslint-disable @typescript-eslint/no-unused-vars */
import { makeStyles } from '@mui/styles';
import { colors } from 'src/utils/light.theme';

const useStyles = makeStyles((theme: any) => ({
	variant_value: {
		height: '2rem',
		width: 'fit-content',
		minWidth: '3.4rem',
		fontSize: '1.2rem',
		textAlign: 'center',
		marginLeft: '0.6rem',
		borderRadius: '2rem',
		padding: '2px 5px',
		fontWeight: 700,
		maxWidth: '8rem',
		display: 'flex',
		justifyContent: 'center',
		whiteSpace: 'nowrap',
	},
	skeleton_container_style: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	selected_variant_value: {
		height: '2rem',
		width: 'fit-content',
		minWidth: '3.4rem',
		fontSize: '1.2rem',
		marginLeft: '0.6rem',
		textAlign: 'center',
		borderRadius: '2rem',
		padding: '2px 5px',
		fontWeight: 700,
		color: 'rgba(0, 0, 0, 0.6)',
		maxWidth: '8rem',
	},
	product_container: {
		position: 'relative',
		...theme?.product?.product_border,
		height: '100%',
	},
	storefront_product_container: {
		position: 'relative',
		...theme?.product?.product_border,
		height: '100%',
		overflow: 'hidden',
		'@media (max-width: 600px)': {
			marginBottom: '1rem',
		},
	},
	product_container_stack: {
		position: 'relative',
		...theme?.product?.product_border,
		height: '100%',
		width: 'calc(100% - 10px) !important',
	},

	// overlay_container_1: {
	// 	width: '50px',
	// 	height: '91%',
	// 	position: 'absolute',
	// 	border: '1px solid #d1d6dd',
	// 	borderRadius: '1.3rem',
	// 	left: ' 20px',
	// 	top: '30px',
	// 	background: '#eef1f7',
	// },
	// overlay_container_2: {
	// 	width: '50px',
	// 	height: ' 93%',
	// 	position: 'absolute',
	// 	left: ' 25px',
	// 	top: '25px',
	// 	background: '#f7f8f8',
	// 	border: '1px solid #d1d6dd',
	// 	borderRadius: '1.3rem',
	// },

	storefront_overlay_container_1: {
		width: '50px',
		height: '100%',
		position: 'absolute',
		border: '1px solid #d1d6dd',
		// borderRadius: '1.3rem',
		background: '#eef1f7',
	},
	storefront_overlay_container_2: {
		width: '50px',
		height: '100%',
		position: 'absolute',
		background: '#f7f8f8',
		border: '1px solid #d1d6dd',
		// borderRadius: '1.3rem',
	},
	stack_container_1: {
		marginLeft: '3px',
		position: 'absolute',
		top: 22,
		left: 10,
		height: '91.8%',
	},
	stack_container_2: {
		marginLeft: '4px',
		position: 'absolute',
		top: 17,
		left: 13,
		height: '94%',
	},
	product_container_image: {
		width: '100%',
		'@media (max-width: 600px)': {
			height: '157px',
			...theme?.product?.product_card_image,
		},
	},
	wishlist_icon: {
		position: 'absolute',
		right: '8px',
		top: '8px',
		zIndex: 1,
	},
	selected_close_icon: {
		position: 'absolute',
		right: '8px',
		top: '8px',
		zIndex: 99,
		backgroundColor: colors.white,
		borderRadius: '100px',
		padding: '4px',
		boxShadow: `0px 4.88px 14.64px 0px ${colors.black_14}`,
		cursor: 'pointer',
		border: `1px solid ${theme?.palette?.secondary[400]}`,
	},
	cart_button: {
		boxShadow: 'none',
		width: '100%',
	},
	product_detail: {
		padding: '0.5rem 1rem',
		cursor: 'pointer',
		// height: '2rem',
		margin: '0.3rem 0rem',
		'@media (max-width: 600px)': {
			paddingInline: '0',
			margin: '0',
		},
	},

	hinge_product_detail: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		overflow: 'hidden',
	},
	ellipsis: {
		marginTop: '0.2rem',
	},
	product_attribute_detail: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		flexWrap: 'nowrap',
		padding: '0.5rem 1rem',
		margin: '0.3rem 0rem',
		cursor: 'pointer',
		height: '2.5rem',
		whiteSpace: 'nowrap',
		overflow: 'hidden',
		...theme?.product?.hinge_product_detail,
		'@media (max-width: 600px)': {
			paddingInline: 0,
		},
	},
	product_attribute_detail_nth: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		flexWrap: 'nowrap',
		padding: '0rem 1rem',
		margin: '0rem',
		cursor: 'pointer',
		height: '2rem',
		whiteSpace: 'nowrap',
		overflow: 'hidden',
		...theme?.product?.hinge_product_detail,
		'@media (max-width: 600px)': {
			paddingInline: 0,
		},
	},
	product_variant_chip: {
		...theme?.product?.product_variant_chip,
	},
	card_loading: {
		backgroundColor: 'rgba(0, 0, 0, 0.3)',
		position: 'absolute',
		width: '100%',
		height: '100%',
		top: 0,
		left: 0,
		zIndex: 1000,
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
	},
	review_checkbox: {
		position: 'absolute',
		right: '12px',
		top: '12px',
		zIndex: 1,
		cursor: 'pointer',
	},
	detail_container: {
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'space-between',
		width: '100%',
	},
	product_image: {
		...theme?.product?.product_image,
		height: '25rem',
		width: '100%',
		objectFit: 'contain',
		position: 'relative',
	},
	image_container: {
		cursor: 'pointer',
		position: 'relative',
		marginBottom: '0.8rem',
	},
	list_circle: {
		marginTop: '-0.1rem',
	},
	hinge_attr_value: {
		display: 'inline-flex',
		cursor: 'pointer',
		backgroundColor: '#f7f8fa',
		padding: '0.5rem 0.6rem',
		marginRight: '0.4rem',
		borderRadius: '0.4rem',
		overflow: 'auto',
	},
	hinge_custom_text: {
		maxWidth: '13.5rem',
		overflow: 'hidden',
		textOverflow: 'ellipsis',
	},
	add_to_button: {
		padding: '1rem',
		boxShadow: 'none',
		maxHeight: '56px',
		'@media (max-width: 600px)': {
			paddingInline: 0,
		},
	},
	wrapping_text: {
		whiteSpace: 'nowrap',
		'@media (max-width: 1000px)': {
			fontSize: '12px !important',
		},
	},

	variant_badge: {
		width: 'fit-content',
		display: 'flex',
		justifyContent: 'flex-end',
	},
	product_name: {
		whiteSpace: 'nowrap',
		overflow: 'hidden',
		textOverflow: 'ellipsis',
		width: '80%',
		...theme?.product?.product_name,
		'@media (max-width: 600px)': {
			display: '-webkit-box',
			'-webkit-line-clamp': 2,
			'-webkit-box-orient': 'vertical',
			minHeight: '30px',
			maxHeight: '40px',
			lineHeight: '16px',
			overflowWrap: 'break-word',
			whiteSpace: 'normal',
			width: '100%',
		},
	},
	product_name_mobile: {
		display: '-webkit-box',
		'-webkit-line-clamp': 2,
		'-webkit-box-orient': 'vertical',
		overflow: 'hidden',
		textOverflow: 'ellipsis',
		minHeight: '30px',
		maxHeight: '40px',
		lineHeight: '16px',
		overflowWrap: 'break-word',
	},
	remove_icon: {
		border: 'none',
		width: '20px',
		height: '20px',
		padding: '7px',
		borderRadius: '50px',
		cursor: 'pointer',
		marginRight: '6px',
	},
	date_chip: {
		width: '160px',
		height: '28px',
		fontSize: '10px',
		borderRadius: '40px',
		position: 'absolute',
		top: '3px',
		zIndex: 2,
		left: '1px',
	},
	add_icon: {
		border: 'none',
		width: '2rem',
		height: '2rem',
		padding: '0.7rem',
		borderRadius: '5rem',
		cursor: 'pointer',
		marginLeft: '0.6rem',
	},
	show_count: {
		outline: 'none',
		fontSize: '1.6rem',
		fontWeight: 700,
		height: '3.4rem',
		lineHeight: '3.4rem',
		borderRadius: '1rem',
		width: '100%',
		cursor: 'pointer',
		textAlign: 'center',
		...theme?.product?.recommanded?.show_count,
	},
	text_overflow: {
		overflow: 'hidden',
		whiteSpace: 'nowrap',
		textOverflow: 'ellipsis',
		maxHeight: '2.5rem',
		alignItems: 'flex-end',
		...theme?.product?.product_id,
		[theme.breakpoints.down('sm')]: {
			textAlign: 'start',
		},
	},
	product_price: {
		...theme?.product?.product_price,
	},
	breadcrumbs_style: {
		...theme?.product?.bread_crumb_styles,
	},
	search_result_heading: {
		marginTop: '16px',
		...theme?.product?.search_result_heading,
	},
	search_results_container: {
		marginBottom: '16px',
		display: 'flex',
		flexDirection: 'column',
		gap: '24px',
		alignItems: 'center',
	},
	filter_icon: {
		zIndex: 100,
		position: 'absolute',
		// width: '100%', // Uncomment if needed
		bottom: 50,
		cursor: 'pointer',
		boxShadow: '0px 3px 5px -1px rgba(0, 0, 0, 0.2), 0px 6px 10px 0px rgba(0, 0, 0, 0.14), 0px 1px 18px 0px rgba(0, 0, 0, 0.12)',
		borderRadius: '50px',
		border: '1px solid rgba(209, 214, 221, 1)',
		display: 'flex',
		width: 'calc(100% - 80px)',
		flexDirection: 'row',
		flexWrap: 'nowrap',
		marginLeft: '2.5rem',
		marginRight: '2.5rem',
	},
	filter_fab: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'space-around',
		width: '100%',
		boxShadow: '0',
		borderBottomRightRadius: '0', // Add border bottom left radius
		borderTopRightRadius: '0',
		height: '24px',
		...theme?.product?.filter_fab,
	},
	product_sku_price: {
		display: 'flex',
		justifyContent: 'space-between',
		maxWidth: '100%',

		'@media (max-width: 650px)': {
			gap: '8px',
			flexDirection: 'column',
			justifyContent: 'flex-start',
			alignItems: 'flex-start',
		},
	},
	review_icon_style: {
		backgroundColor: colors.white,
		borderRadius: '2.1px',
	},
}));

export default useStyles;
