export const template = {
	counters: {
		u_row: 16,
		u_column: 28,
		u_content_text: 20,
		u_content_image: 27,
		u_content_button: 3,
		u_content_social: 3,
		u_content_divider: 3,
		u_content_heading: 5,
	},
	body: {
		id: 'v0MaoWJhDK',
		rows: [
			{
				id: '6ZA7MgBW8o',
				cells: [1],
				columns: [
					{
						id: 'ks8Zzk1OS9',
						contents: [
							{
								id: 'wFm5698jcE',
								type: 'image',
								values: {
									containerPadding: '0px',
									anchor: '',
									src: {
										url: 'https://assets.unlayer.com/projects/221483/1723551815784-Visual%20Design%20Creatives%20(1).png',
										width: 1055,
										height: 443,
										id: 23394690,
										size: 68561,
										contentType: 'image/png',
									},
									textAlign: 'center',
									altText: '',
									action: {
										name: 'web',
										values: {
											href: '',
											target: '_blank',
										},
									},
									hideDesktop: false,
									displayCondition: null,
									_meta: {
										htmlID: 'u_content_image_27',
										description: '',
										htmlClassNames: 'u_content_image',
									},
									selectable: true,
									draggable: true,
									duplicatable: true,
									deletable: true,
									hideable: true,
									pending: false,
								},
							},
							{
								id: 'L2xqHRcRZq',
								type: 'text',
								values: {
									containerPadding: '24px 48px',
									anchor: '',
									fontFamily: {
										url: 'https://fonts.googleapis.com/css?family=Cabin:400,700',
										label: 'Cabin',
										value: "'Cabin',sans-serif",
										weights: [400, 700],
										defaultFont: true,
									},
									fontSize: '14px',
									textAlign: 'left',
									lineHeight: '140%',
									linkStyle: {
										inherit: true,
										linkColor: '#0000ee',
										linkHoverColor: '#0000ee',
										linkUnderline: true,
										linkHoverUnderline: true,
									},
									hideDesktop: false,
									displayCondition: null,
									_meta: {
										htmlID: 'u_content_text_20',
										description: '',
										htmlClassNames: 'u_content_text',
									},
									selectable: true,
									draggable: true,
									duplicatable: true,
									deletable: true,
									hideable: true,
									text: '<p style="line-height: 140%;">The [module name] sync from [origin source] to [destination source] was successfully completed on [date] at [time].</p>\n<p style="line-height: 140%;">Click <a rel="noopener noreferrer" href="mailto:help@wizcommerce.com" target="_blank" data-remove-tab-index="true" aria-haspopup="menu" data-sk="tooltip_parent" data-stringify-link="mailto:help@wizcommerce.com">here</a> to view the file. </p>\n<p style="line-height: 140%;"> </p>\n<p style="line-height: 140%;"><span aria-label="" data-stringify-type="paragraph-break" style="line-height: 19.6px;"></span>Incase of any queries, please reach out to <a rel="noopener noreferrer" href="mailto:help@wizcommerce.com" target="_blank" data-stringify-link="mailto:help@wizcommerce.com" data-sk="tooltip_parent" aria-haspopup="menu" data-remove-tab-index="true">help@wizcommerce.com<span aria-label="(opens in new tab)" data-qa="opens-in-new-tab" style="line-height: 19.6px;"></span></a>.</p>',
									_override: {
										mobile: {
											containerPadding: '10px 20px',
										},
									},
								},
							},
						],
						values: {
							_meta: {
								htmlID: 'u_column_20',
								htmlClassNames: 'u_column',
							},
							border: {},
							padding: '0px',
							borderRadius: '0px',
							backgroundColor: '',
						},
					},
				],
				values: {
					displayCondition: null,
					columns: false,
					backgroundColor: '',
					columnsBackgroundColor: '#ffffff',
					backgroundImage: {
						url: '',
						fullWidth: true,
						repeat: 'no-repeat',
						size: 'custom',
						position: 'center',
					},
					padding: '0px',
					anchor: '',
					hideDesktop: false,
					_meta: {
						htmlID: 'u_row_12',
						htmlClassNames: 'u_row',
					},
					selectable: true,
					draggable: true,
					duplicatable: true,
					deletable: true,
					hideable: true,
				},
			},
			{
				id: '-H_yg4ETe8',
				cells: [1],
				columns: [
					{
						id: 'x9nz-8czqw',
						contents: [
							{
								id: 'XRy3Kw2NMm',
								type: 'text',
								values: {
									containerPadding: '7px',
									anchor: '',
									fontFamily: {
										url: 'https://fonts.googleapis.com/css?family=Cabin:400,700',
										label: 'Cabin',
										value: "'Cabin',sans-serif",
										weights: [400, 700],
										defaultFont: true,
									},
									fontSize: '14px',
									textAlign: 'center',
									lineHeight: '140%',
									linkStyle: {
										inherit: false,
										linkColor: '#0000ee',
										linkHoverColor: '#0000ee',
										linkUnderline: true,
										linkHoverUnderline: true,
										body: false,
									},
									hideDesktop: false,
									displayCondition: null,
									_meta: {
										htmlID: 'u_content_text_19',
										htmlClassNames: 'u_content_text',
									},
									selectable: true,
									draggable: true,
									duplicatable: true,
									deletable: true,
									hideable: true,
									text: '<p style="line-height: 140%;">Powered by <span style="text-decoration: underline; line-height: 19.6px; color: #16885f;"><span style="line-height: 19.6px;">Wizcommerce</span></span></p>',
								},
							},
						],
						values: {
							_meta: {
								htmlID: 'u_column_21',
								htmlClassNames: 'u_column',
							},
							border: {},
							padding: '0px',
							borderRadius: '0px',
							backgroundColor: '#e1e7e8',
						},
					},
				],
				values: {
					displayCondition: null,
					columns: false,
					backgroundColor: '',
					columnsBackgroundColor: '',
					backgroundImage: {
						url: '',
						fullWidth: true,
						repeat: 'no-repeat',
						size: 'custom',
						position: 'center',
					},
					padding: '0px',
					anchor: '',
					hideDesktop: false,
					_meta: {
						htmlID: 'u_row_13',
						htmlClassNames: 'u_row',
					},
					selectable: true,
					draggable: true,
					duplicatable: true,
					deletable: true,
					hideable: true,
				},
			},
		],
		headers: [],
		footers: [],
		values: {
			popupPosition: 'center',
			popupWidth: '600px',
			popupHeight: 'auto',
			borderRadius: '10px',
			contentAlign: 'center',
			contentVerticalAlign: 'center',
			contentWidth: 600,
			fontFamily: {
				label: 'Raleway',
				value: "'Raleway',sans-serif",
				url: 'https://fonts.googleapis.com/css?family=Raleway:400,700',
				weights: null,
				defaultFont: true,
			},
			textColor: '#000000',
			popupBackgroundColor: '#FFFFFF',
			popupBackgroundImage: {
				url: '',
				fullWidth: true,
				repeat: 'no-repeat',
				size: 'cover',
				position: 'center',
			},
			popupOverlay_backgroundColor: 'rgba(0, 0, 0, 0.1)',
			popupCloseButton_position: 'top-right',
			popupCloseButton_backgroundColor: '#DDDDDD',
			popupCloseButton_iconColor: '#000000',
			popupCloseButton_borderRadius: '0px',
			popupCloseButton_margin: '0px',
			popupCloseButton_action: {
				name: 'close_popup',
				attrs: {
					onClick: "document.querySelector('.u-popup-container').style.display = 'none';",
				},
			},
			language: {},
			backgroundColor: '#ffffff',
			preheaderText: '',
			linkStyle: {
				body: true,
				linkColor: '#0000ee',
				linkHoverColor: '#0000ee',
				linkUnderline: true,
				linkHoverUnderline: true,
			},
			backgroundImage: {
				url: '',
				fullWidth: true,
				repeat: 'no-repeat',
				size: 'custom',
				position: 'center',
			},
			_meta: {
				htmlID: 'u_body',
				htmlClassNames: 'u_body',
			},
		},
	},
	schemaVersion: 16,
};
