/* eslint-disable @typescript-eslint/no-unused-vars */
import { makeStyles } from '@mui/styles';

const { VITE_APP_REPO } = import.meta.env;
const is_ultron = VITE_APP_REPO === 'ultron';

const useStyles = makeStyles((theme: any) => ({
	variant_value: {
		height: '2rem',
		width: '3.4rem',
		minWidth: '3.4rem',
		fontSize: '1.2rem',
		textAlign: 'center',
		marginLeft: '0.6rem',
		borderRadius: '2rem',
		padding: '2px',
		fontWeight: 700,
	},
	wishlist_icon: {
		position: 'absolute',
		right: is_ultron ? '6px' : '36px',
		top: is_ultron ? '0px' : '8px',
		zIndex: 1,
		cursor: 'pointer',
	},
	review_checkbox: {
		position: 'absolute',
		right: '12px',
		top: '12px',
		zIndex: 1,
		cursor: 'pointer',
	},
	review_icon_style: {
		backgroundColor: '#fff',
		borderRadius: '2.1px',
	},
	selected_variant_value: {
		height: '2rem',
		width: '3.4rem',
		minWidth: '3.4rem',
		fontSize: '1.2rem',
		marginLeft: '0.6rem',
		textAlign: 'center',
		borderRadius: '2rem',
		padding: '1px',
		fontWeight: 700,
		...theme?.product?.recommanded?.selected_variant_value,
	},
	product_container: {
		height: '100%',
		borderRadius: '1.3rem',
		minWidth: '28rem',
		maxWidth: '28rem',
		border: '1px solid #d1d6dd',
		position: 'relative',
		...theme?.product_details?.product_image_card,
	},
	cart_button: {
		boxShadow: 'none',
		width: '100%',
	},
	card_custom_style: {
		...theme?.product_details?.card_custom_style,
	},
	product_detail: {
		cursor: 'pointer',
		...theme?.product_details?.card_template_row,
	},
	hinge_product_detail: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		overflow: 'hidden',
	},
	ellipsis: {
		marginTop: '0.2rem',
	},
	product_attribute_detail: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		flexWrap: 'nowrap',
		padding: '0.5rem 1rem',
		margin: '0.3rem 0rem',
		cursor: 'pointer',
		height: '3rem',
		whiteSpace: 'nowrap',
		overflow: 'hidden',
	},
	product_attribute_detail_nth: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		flexWrap: 'nowrap',
		padding: '0rem',
		margin: '0rem 1rem',
		cursor: 'pointer',
		height: '3rem',
		whiteSpace: 'nowrap',
		overflow: 'hidden',
	},
	hinge_attr_value: {
		display: 'inline-flex',
		cursor: 'pointer',
		backgroundColor: '#F7F8FA',
		padding: '0.5rem 0.6rem',
		marginRight: '0.4rem',
		borderRadius: '0.4rem',
		overflow: 'auto',
	},
	hinge_custom_text: {
		maxWidth: '13.5rem',
		overflow: 'hidden',
		textOverflow: 'ellipsis',
	},
	detail_container: {
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'space-between',
		width: '100%',
	},
	product_image: {
		borderRadius: '1.2rem 1.2rem 0 0',
		height: '25rem',
		maxHeight: '25rem',
		width: '25rem',
		objectFit: 'contain',
		position: 'relative',
		...theme?.product_details?.product_image,
	},
	image_container: {
		cursor: 'pointer',
		position: 'relative',
		marginBottom: '0.8rem',
	},
	list_circle: {
		marginTop: '-0.1rem',
		...theme?.product?.product_template?.list_circle,
	},
	add_to_button: {
		padding: '1rem',
		boxShadow: 'none',
	},
	variant_badge: {
		width: '20%',
		display: 'flex',
		justifyContent: 'flex-end',
	},
	product_card_info: {
		...theme?.product_details?.product_card_info,
		display: 'flex',
		alignItems: 'center',
		gap: '5px',
	},
	product_name: {
		whiteSpace: 'nowrap',
		overflow: 'hidden',
		textOverflow: 'ellipsis',
		width: '80%',
		...theme?.product_details?.sku_id_tert,
		...theme?.product_details?.product_name,
	},
	remove_icon: {
		border: 'none',
		width: '20px',
		height: '20px',
		padding: '7px',
		borderRadius: '50px',
		cursor: 'pointer',
		marginRight: '6px',
		...theme?.product?.recommanded?.remove_icon,
	},
	add_icon: {
		border: 'none',
		width: '2rem',
		height: '2rem',
		padding: '0.7rem',
		borderRadius: '5rem',
		cursor: 'pointer',
		marginLeft: '0.6rem',
		...theme?.product?.recommanded?.add_icon,
	},
	show_count: {
		outline: 'none',
		fontSize: '1.6rem',
		fontWeight: 700,
		height: '3.4rem',
		borderRadius: '1rem',
		width: '100%',
		cursor: 'pointer',
		textAlign: 'center',
		...theme?.product?.recommanded?.show_count,
	},
	text_overflow: {
		overflow: 'hidden',
		whiteSpace: 'nowrap',
		textOverflow: 'ellipsis',
		maxHeight: '2rem',
		...theme?.product?.recommanded?.sku_id_text,
	},
}));

export default useStyles;
