import { formattedValue } from 'src/utils/common';

export const SECTION_DEFAULTS = ['contacts', 'addresses', 'payment_methods', 'other_details', 'tax_preferences'];
export const buyer_sections: any = {
	basic_details: {
		columns: [
			{
				suppressMenu: true,
				field: 'name',
				headerName: 'Name',
				flex: 1,
				editable: false,
				clickable: false,
				type: 'text',
				tooltipField: 'name',
			},
			{
				suppressMenu: true,
				field: 'type',
				flex: 1,
				headerName: 'Dtype',
				editable: false,
				dtype: 'text',
				hideFilter: true,
			},
			{
				suppressMenu: true,
				field: 'required',
				headerName: 'Mandatory',
				flex: 1,
				editable: false,
				disable: true,
				dtype: 'toggle',
			},
			{
				headerName: 'Quick Add',
				suppressMenu: true,
				field: 'is_quick_add',
				flex: 1,
				cellRenderer: 'agCheckboxCellRenderer',
				cellEditor: 'agCheckboxCellEditor',
				editable: false,
				disable: true,
			},
			{
				headerName: 'To be included',
				suppressMenu: true,
				field: 'is_display',
				flex: 1,
				cellRenderer: 'agCheckboxCellRenderer',
				cellEditor: 'agCheckboxCellEditor',
				editable: false,
				disable: true,
			},
		],
	},
	contacts: {
		columns: [
			{
				suppressMenu: true,
				field: 'name',
				headerName: 'Name',
				flex: 1,
				editable: false,
				clickable: false,
				type: 'text',
				tooltipField: 'name',
			},
			{
				suppressMenu: true,
				field: 'type',
				flex: 1,
				headerName: 'Dtype',
				editable: false,
				dtype: 'text',
				hideFilter: true,
			},
			{
				headerName: 'Mandatory',
				suppressMenu: true,
				field: 'required',
				flex: 1,
				cellRenderer: 'agCheckboxCellRenderer',
				cellEditor: 'agToggleCellEditor',
				editable: false,
				hideFilter: true,
				disable: true,
			},
			{
				headerName: 'To be included',
				suppressMenu: true,
				field: 'is_display',
				flex: 1,
				cellRenderer: 'agCheckboxCellRenderer',
				cellEditor: 'agCheckboxCellEditor',
				editable: false,
				disable: true,
			},
		],
	},
	addresses: {
		columns: [
			{
				suppressMenu: true,
				field: 'name',
				headerName: 'Name',
				flex: 1,
				editable: false,
				clickable: false,
				type: 'text',
				tooltipField: 'name',
			},
			{
				suppressMenu: true,
				field: 'type',
				flex: 1,
				headerName: 'Dtype',
				editable: false,
				dtype: 'text',
				hideFilter: true,
			},
			{
				headerName: 'Required in billing',
				suppressMenu: true,
				field: 'required_in_billing',
				flex: 1,
				cellRenderer: 'agCheckboxCellRenderer',
				cellEditor: 'agToggleCellEditor',
				editable: false,
				disable: true,
			},
			{
				headerName: 'Included in billing',
				suppressMenu: true,
				field: 'included_in_billing',
				flex: 1,
				cellRenderer: 'agCheckboxCellRenderer',
				cellEditor: 'agCheckboxCellEditor',
				editable: false,
				disable: true,
			},
			{
				headerName: 'Required in shipping',
				suppressMenu: true,
				field: 'required_in_shipping',
				flex: 1,
				cellRenderer: 'agCheckboxCellRenderer',
				cellEditor: 'agToggleCellEditor',
				editable: false,
				disable: true,
			},
			{
				headerName: 'Included in shipping',
				suppressMenu: true,
				field: 'included_in_shipping',
				flex: 1,
				cellRenderer: 'agCheckboxCellRenderer',
				cellEditor: 'agCheckboxCellEditor',
				editable: false,
				disable: true,
			},
		],
	},

	preferences: {
		columns: [
			{
				suppressMenu: true,
				field: 'name',
				headerName: 'Name',
				flex: 1,
				editable: false,
				clickable: false,
				type: 'text',
				tooltipField: 'name',
			},
			{
				suppressMenu: true,
				field: 'type',
				flex: 1,
				headerName: 'Dtype',
				editable: false,
				dtype: 'text',
				hideFilter: true,
			},
			{
				suppressMenu: true,
				field: 'value',
				headerName: 'Default Value',
				flex: 1,
				editable: false,
				dtype: 'text',
				hideFilter: true,
				minWidth: 200,
				valueFormatter: (params: any) => {
					const formatted_value = formattedValue(params?.value, params?.node?.data);
					return formatted_value;
				},
			},
			{
				headerName: 'Mandatory',
				suppressMenu: true,
				field: 'required',
				flex: 1,
				cellRenderer: 'agCheckboxCellRenderer',
				cellEditor: 'agToggleCellEditor',
				editable: false,
				disable: true,
			},
			{
				headerName: 'Quick Add',
				suppressMenu: true,
				field: 'is_quick_add',
				flex: 1,
				cellRenderer: 'agCheckboxCellRenderer',
				cellEditor: 'agCheckboxCellEditor',
				editable: false,
				disable: true,
			},
			{
				headerName: 'To be included',
				suppressMenu: true,
				field: 'is_display',
				flex: 1,
				cellRenderer: 'agCheckboxCellRenderer',
				cellEditor: 'agCheckboxCellEditor',
				editable: false,
				disable: true,
			},
		],
	},
	other_details: {
		columns: [
			{
				suppressMenu: true,
				field: 'name',
				headerName: 'Name',
				flex: 1,
				editable: false,
				clickable: false,
				type: 'text',
				tooltipField: 'name',
			},
			{
				suppressMenu: true,
				field: 'type',
				flex: 1,
				headerName: 'Dtype',
				editable: false,
				dtype: 'text',
				hideFilter: true,
			},
			{
				suppressMenu: true,
				field: 'value',
				headerName: 'Default Value',
				flex: 1,
				editable: false,
				dtype: 'text',
				hideFilter: true,
				minWidth: 200,
				valueFormatter: (params: any) => {
					const formatted_value = formattedValue(params?.value, params?.node?.data);
					return formatted_value;
				},
			},
			{
				headerName: 'Mandatory',
				suppressMenu: true,
				field: 'required',
				flex: 1,
				cellRenderer: 'agCheckboxCellRenderer',
				cellEditor: 'agToggleCellEditor',
				editable: false,
				disable: true,
			},
			{
				headerName: 'To be included',
				suppressMenu: true,
				field: 'is_display',
				flex: 1,
				cellRenderer: 'agCheckboxCellRenderer',
				cellEditor: 'agCheckboxCellEditor',
				editable: false,
				disable: true,
			},
		],
	},
	custom_fields: {
		columns: [
			{
				suppressMenu: true,
				field: 'name',
				headerName: 'Name',
				flex: 1,
				editable: false,
				clickable: false,
				type: 'text',
				tooltipField: 'name',
			},
			{
				suppressMenu: true,
				field: 'type',
				flex: 1,
				headerName: 'Dtype',
				editable: false,
				dtype: 'text',
				hideFilter: true,
			},
			{
				suppressMenu: true,
				field: 'value',
				headerName: 'Default Value',
				flex: 1,
				editable: false,
				dtype: 'text',
				hideFilter: true,
				minWidth: 200,
				valueFormatter: (params: any) => {
					const formatted_value = formattedValue(params?.value, params?.node?.data);
					return formatted_value;
				},
			},
			{
				headerName: 'Mandatory',
				suppressMenu: true,
				field: 'required',
				flex: 1,
				cellRenderer: 'agCheckboxCellRenderer',
				cellEditor: 'agToggleCellEditor',
				editable: false,
				disable: true,
			},
			{
				headerName: 'To be included',
				suppressMenu: true,
				field: 'is_display',
				flex: 1,
				cellRenderer: 'agCheckboxCellRenderer',
				cellEditor: 'agCheckboxCellEditor',
				editable: false,
				disable: true,
			},
		],
	},
	payment_methods: {
		columns: [
			{
				suppressMenu: true,
				field: 'name',
				headerName: 'Name',
				flex: 1,
				editable: false,
				clickable: false,
				type: 'text',
				tooltipField: 'name',
			},
			{
				suppressMenu: true,
				field: 'type',
				flex: 1,
				headerName: 'Dtype',
				editable: false,
				dtype: 'text',
				hideFilter: true,
			},
			{
				suppressMenu: true,
				field: 'value',
				headerName: 'Default Value',
				flex: 1,
				editable: false,
				dtype: 'text',
				hideFilter: true,
				valueFormatter: (params: any) => {
					const formatted_value = formattedValue(params?.value, params?.node?.data);
					return formatted_value;
				},
			},
		],
	},
};
