export const mock = [
	{
		label: 'Products',
		value: 'products',
		sub_entities: [],
		image: 'https://sourcerer.tech/assets/65475616-8765-47b3-bdb0-cae3e86eb45c',
		selected_image: 'https://sourcerer.tech/assets/dcaf9049-2991-4f1e-933a-03cba84c0ea8',
		disabled: false,
		can_import: true,
		can_export: true,
	},
	{
		label: 'Categories',
		value: 'categories',
		sub_entities: [],
		image: 'https://sourcerer.tech/assets/4ab37f5a-faa7-49b2-8d94-23e1aa00bcac',
		selected_image: 'https://sourcerer.tech/assets/146456af-a02e-4d06-b822-d8b131151601',
		disabled: false,
		can_import: true,
		can_export: true,
	},
	{
		label: 'Collections',
		value: 'collections',
		sub_entities: [],
		image: 'https://sourcerer.tech/assets/1bba4f92-34df-4de2-86b1-78343a5bdcf2',
		selected_image: 'https://sourcerer.tech/assets/b24fcb8d-a953-42ee-897f-10561d0c073a',
		disabled: false,
		can_import: true,
		can_export: true,
	},
	{
		label: 'Inventory',
		value: 'inventory',
		sub_entities: [],
		image: 'https://sourcerer.tech/assets/afb060b5-e811-451c-adc5-a9603791b117',
		selected_image: 'https://sourcerer.tech/assets/2f30599e-bba9-48a6-bc77-44a47aafccbf',
		disabled: false,
		can_import: true,
		can_export: true,
	},
	{
		label: 'Buyers',
		value: 'buyers',
		sub_entities: [
			{
				label: 'Buyers',
				value: 'basic_information',
				image: '',
				selected_image: '',
				disabled: false,
				can_import: true,
				can_export: true,
			},
			{
				label: 'Contacts',
				value: 'contacts',
				image: '',
				selected_image: '',
				disabled: false,
				can_import: true,
				can_export: true,
			},
			{
				label: 'Addresses',
				value: 'addresses',
				image: '',
				selected_image: '',
				disabled: false,
				can_import: true,
				can_export: true,
			},
		],
		image: 'https://sourcerer.tech/assets/25be8555-2cfb-4feb-aff7-fd80bcbfef35',
		selected_image: 'https://sourcerer.tech/assets/0dac5a60-866c-47d2-afb7-96ae9d3c15e2',
		disabled: false,
		can_import: true,
		can_export: true,
	},
	{
		label: 'Orders & Quotes',
		value: 'documents',
		sub_entities: [
			{
				label: 'Orders & Quotes',
				value: 'order_quote',
				image: '',
				selected_image: '',
				disabled: false,
				can_import: true,
				can_export: true,
			},
			{
				label: 'Orders & Quotes items',
				value: 'order_quote_items',
				image: '',
				selected_image: '',
				disabled: false,
				can_import: true,
				can_export: true,
			},
		],
		image: 'https://sourcerer.tech/assets/4e984c30-8f91-4ef5-997f-6687942940ec',
		selected_image: 'https://sourcerer.tech/assets/c24eb743-8f47-444f-84f1-857dbe806787',
		disabled: false,
		can_import: true,
		can_export: true,
	},
	{
		label: 'Modifiers',
		value: 'modifiers',
		sub_entities: [
			{
				label: 'Modifiers Setup',
				value: 'modifiers',
				image: '',
				selected_image: '',
				disabled: false,
				can_import: true,
				can_export: true,
			},
			{
				label: 'Product & Modifiers Mapping',
				value: 'product_modifiers',
				image: '',
				selected_image: '',
				disabled: false,
				can_import: true,
				can_export: true,
			},
		],
		image: 'https://sourcerer.tech/assets/eecdeebd-0254-4729-8d07-e21e513dd5d6',
		selected_image: 'https://sourcerer.tech/assets/845059de-6225-420d-9a80-80bb31d58552',
		disabled: false,
		can_import: true,
		can_export: true,
	},
];
