import { OrdersActionComp } from './Components/OrdersActionComp';

export const store_front_order_columns = ['system_id', 'document_status', 'total_value', 'created_at', 'action'];
export const store_front_invoice_columns = [
	'system_id',
	'order_number',
	'document_status',
	'created_at',
	'due_date',
	'total_value',
	'balance',
	'action',
];

export const columnDefs = [
	{
		headerName: 'Order ID',
		field: 'system_id',
		resizable: true,
		headerStyle: {},
		unSortIcon: true,
		lockPinned: false,
		clickable: true,
		hide: false,
		type: 'imageText2',
		dtype: 'imageText2',
		filter: 'agTextColumnFilter',
		sortable: true,
		hideFilter: true,
		minWidth: 200,
		editable: false,
		flex: 1,
		headerClass: 'custom-header-color-odd',
		cellEditor: {
			type: {},
			compare: null,
		},
		menuTabs: ['generalMenuTab'],
		cellEditorPopup: true,
		cellStyle: {
			width: 200,
			minWidth: 200,
		},
		cellRendererParams: {
			type: 'imageText2',
			headerName: 'Reference ID',
			field: 'system_id',
			resizable: true,
			headerStyle: {},
			unSortIcon: true,
			lockPinned: true,
			clickable: true,
			hide: false,
			dtype: 'imageText2',
			sortable: true,
			hideFilter: true,
			minWidth: 200,
			editable: false,
			flex: 1,
			headerClass: 'custom-header-color-odd',
			cellEditor: {
				type: {},
				compare: null,
			},
			menuTabs: ['generalMenuTab'],
			cellEditorPopup: true,
			cellStyle: {
				width: 200,
				minWidth: 200,
			},
		},
		headerComponentParams: {
			template:
				'<div class="ag-cell-label-container" role="presentation">\n\t\t\t<span ref="eMenu" class="ag-header-icon ag-header-cell-menu-button"></span>\n\t\t\t<div ref="eLabel" class="ag-header-cell-label" role="presentation">\n\t\t\t\t<span ref="eFilter" class="ag-header-icon ag-filter-icon"></span>\n\t\t\t\t<span ref="eText" class="ag-header-cell-text" role="columnheader"></span>\n\t\t\t\t<span ref="eSortAsc" class="ag-header-icon ag-sort-ascending-icon ag-hidden"></span>\n\t\t\t\t<span ref="eSortDesc" class="ag-header-icon ag-sort-descending-icon ag-hidden"></span>\n\t\t\t\t<span ref="eSortMixed" class="ag-header-icon ag-sort-mixed-icon ag-hidden"></span>\n\t\t\t\t<span ref="eSortNone" class="ag-header-icon ag-sort-none-icon ag-hidden"></span>\n\t\t\t\t<span ref="eSortOrder" class="ag-header-icon ag-sort-order ag-hidden"></span>\n\t\t\t</div>\n\t\t</div>',
		},
		tooltipField: 'system_id',
		filterParams: {
			filterOptions: ['contains', 'notContains', 'equals', 'blank', 'notBlank'],
			buttons: ['reset', 'apply'],
			closeOnApply: true,
			maxNumConditions: 1,
		},
	},
	{
		headerName: 'Status',
		field: 'document_status',
		resizable: true,
		headerStyle: {},
		unSortIcon: true,
		lockPinned: false,
		clickable: false,
		hide: false,
		type: 'status',
		dtype: 'status',
		filter: 'agSetColumnFilter',
		sortable: true,
		hideFilter: true,
		minWidth: 200,
		editable: false,
		onCellClicked: '',
		flex: 1,
		filterParams: {
			filterOptions: ['contains'],
			buttons: ['reset', 'apply'],
			closeOnApply: true,
			maxNumConditions: 1,
		},
		headerClass: 'custom-header-color-odd',
		cellEditor: {
			type: {},
			compare: null,
		},
		menuTabs: ['generalMenuTab'],
		cellEditorPopup: true,
		cellStyle: {
			width: 200,
			minWidth: 200,
		},
		cellRendererParams: {
			type: 'status',
			headerName: 'Status',
			field: 'document_status',
			resizable: true,
			headerStyle: {},
			unSortIcon: true,
			lockPinned: false,
			clickable: false,
			hide: false,
			dtype: 'status',
			sortable: true,
			hideFilter: true,
			minWidth: 200,
			editable: false,
			onCellClicked: '',
			filterParams: {},
			headerClass: 'custom-header-color-odd',
			cellEditor: {
				type: {},
				compare: null,
			},
			menuTabs: ['generalMenuTab'],
			cellEditorPopup: true,
			cellStyle: {
				width: 200,
				minWidth: 200,
			},
		},
		headerComponentParams: {
			template:
				'<div class="ag-cell-label-container" role="presentation">\n\t\t\t<span ref="eMenu" class="ag-header-icon ag-header-cell-menu-button"></span>\n\t\t\t<div ref="eLabel" class="ag-header-cell-label" role="presentation">\n\t\t\t\t<span ref="eFilter" class="ag-header-icon ag-filter-icon"></span>\n\t\t\t\t<span ref="eText" class="ag-header-cell-text" role="columnheader"></span>\n\t\t\t\t<span ref="eSortAsc" class="ag-header-icon ag-sort-ascending-icon ag-hidden"></span>\n\t\t\t\t<span ref="eSortDesc" class="ag-header-icon ag-sort-descending-icon ag-hidden"></span>\n\t\t\t\t<span ref="eSortMixed" class="ag-header-icon ag-sort-mixed-icon ag-hidden"></span>\n\t\t\t\t<span ref="eSortNone" class="ag-header-icon ag-sort-none-icon ag-hidden"></span>\n\t\t\t\t<span ref="eSortOrder" class="ag-header-icon ag-sort-order ag-hidden"></span>\n\t\t\t</div>\n\t\t</div>',
		},
	},
	{
		headerName: 'Order value',
		field: 'total_value',
		resizable: true,
		headerStyle: {},
		unSortIcon: true,
		lockPinned: false,
		clickable: false,
		hide: false,
		type: 'currency',
		dtype: 'currency',
		filter: 'agNumberColumnFilter',
		sortable: true,
		hideFilter: true,
		minWidth: 200,
		editable: false,
		flex: 1,
		onCellClicked: '',
		headerClass: 'custom-header-color-even',
		cellEditor: {
			type: {},
			compare: null,
		},
		menuTabs: ['generalMenuTab'],
		cellEditorPopup: true,
		cellStyle: {
			width: 200,
			minWidth: 200,
		},
		cellRendererParams: {
			type: 'currency',
			headerName: 'Order value',
			field: 'total_value',
			resizable: true,
			headerStyle: {},
			unSortIcon: true,
			lockPinned: false,
			clickable: false,
			hide: false,
			dtype: 'currency',
			sortable: true,
			hideFilter: true,
			minWidth: 200,
			editable: false,
			onCellClicked: '',
			headerClass: 'custom-header-color-even',
			cellEditor: {
				type: {},
				compare: null,
			},
			menuTabs: ['generalMenuTab'],
			cellEditorPopup: true,
			cellStyle: {
				width: 200,
				minWidth: 200,
			},
		},
		headerComponentParams: {
			template:
				'<div class="ag-cell-label-container" role="presentation">\n\t\t\t<span ref="eMenu" class="ag-header-icon ag-header-cell-menu-button"></span>\n\t\t\t<div ref="eLabel" class="ag-header-cell-label" role="presentation">\n\t\t\t\t<span ref="eFilter" class="ag-header-icon ag-filter-icon"></span>\n\t\t\t\t<span ref="eText" class="ag-header-cell-text" role="columnheader"></span>\n\t\t\t\t<span ref="eSortAsc" class="ag-header-icon ag-sort-ascending-icon ag-hidden"></span>\n\t\t\t\t<span ref="eSortDesc" class="ag-header-icon ag-sort-descending-icon ag-hidden"></span>\n\t\t\t\t<span ref="eSortMixed" class="ag-header-icon ag-sort-mixed-icon ag-hidden"></span>\n\t\t\t\t<span ref="eSortNone" class="ag-header-icon ag-sort-none-icon ag-hidden"></span>\n\t\t\t\t<span ref="eSortOrder" class="ag-header-icon ag-sort-order ag-hidden"></span>\n\t\t\t</div>\n\t\t</div>',
		},
		filterParams: {
			filterOptions: ['equals', 'lessThanOrEqual', 'greaterThanOrEqual', 'lessThan', 'greaterThan', 'inRange'],
			buttons: ['reset', 'apply'],
			closeOnApply: true,
			maxNumConditions: 1,
		},
	},
	{
		headerName: 'Created On',
		field: 'created_at',
		resizable: true,
		headerStyle: {},
		unSortIcon: true,
		lockPinned: false,
		clickable: false,
		hide: false,
		type: 'unixdate',
		dtype: 'unixdate',
		filter: 'agDateColumnFilter',
		sortable: true,
		hideFilter: true,
		minWidth: 200,
		flex: 1,
		editable: false,
		onCellClicked: '',
		headerClass: 'custom-header-color-even',
		cellEditor: {
			type: {},
			compare: null,
		},
		menuTabs: ['generalMenuTab'],
		cellEditorPopup: true,
		cellStyle: {
			width: 200,
			minWidth: 200,
		},
		cellRendererParams: {
			type: 'unixdate',
			headerName: 'Created On',
			field: 'created_at',
			resizable: true,
			headerStyle: {},
			unSortIcon: true,
			lockPinned: false,
			clickable: false,
			hide: false,
			dtype: 'unixdate',
			sortable: true,
			hideFilter: true,
			minWidth: 200,
			editable: false,
			onCellClicked: '',
			headerClass: 'custom-header-color-even',
			cellEditor: {
				type: {},
				compare: null,
			},
			menuTabs: ['generalMenuTab'],
			cellEditorPopup: true,
			cellStyle: {
				width: 200,
				minWidth: 200,
			},
		},
		headerComponentParams: {
			template:
				'<div class="ag-cell-label-container" role="presentation">\n\t\t\t<span ref="eMenu" class="ag-header-icon ag-header-cell-menu-button"></span>\n\t\t\t<div ref="eLabel" class="ag-header-cell-label" role="presentation">\n\t\t\t\t<span ref="eFilter" class="ag-header-icon ag-filter-icon"></span>\n\t\t\t\t<span ref="eText" class="ag-header-cell-text" role="columnheader"></span>\n\t\t\t\t<span ref="eSortAsc" class="ag-header-icon ag-sort-ascending-icon ag-hidden"></span>\n\t\t\t\t<span ref="eSortDesc" class="ag-header-icon ag-sort-descending-icon ag-hidden"></span>\n\t\t\t\t<span ref="eSortMixed" class="ag-header-icon ag-sort-mixed-icon ag-hidden"></span>\n\t\t\t\t<span ref="eSortNone" class="ag-header-icon ag-sort-none-icon ag-hidden"></span>\n\t\t\t\t<span ref="eSortOrder" class="ag-header-icon ag-sort-order ag-hidden"></span>\n\t\t\t</div>\n\t\t</div>',
		},
		filterParams: {
			filterOptions: ['equals', 'lessThanOrEqual', 'greaterThanOrEqual', 'lessThan', 'greaterThan', 'inRange'],
			inRangeFloatingFilterDateFormat: 'D MMM YYYY',
			buttons: ['reset', 'apply'],
			closeOnApply: true,
			maxNumConditions: 1,
		},
	},
	{
		headerName: 'Actions',
		field: 'action',
		editable: false,
		filter: false,
		dtype: 'action',
		resizable: false,
		cellStyle: {
			background: 'transparent',
			width: '119px',
			justifyContent: 'center',
			alignItems: 'center',
			minWidth: '119px',
			textAlign: 'center',
			borderRadius: '8px',
		},
		sortable: false,
		headerStyle: {
			width: '120px',
		},
		width: 120,
		minWidth: 120,
		suppressMenu: true,
		hideFilter: true,
		cellRenderer: OrdersActionComp,
	},
];
