export const DETAILS_BUYER_FORM = {
	sections: [
		{
			attributes: [
				{
					id: 'company_name',
					name: 'Company name',
					priority: 0,
					required: true,
					type: 'text',
					value: '',
					is_quick_add: true,
					is_display: true,
				},
				{
					id: 'display_name',
					name: 'Display name',
					priority: 1,
					required: false,
					type: 'text',
					value: '',
					is_quick_add: true,
					is_display: true,
				},
				{
					id: 'sales_reps',
					name: 'Sales Rep',
					options: [{ label: '', value: '' }],
					priority: 2,
					required: true,
					type: 'select',
					value: '',
					is_quick_add: true,
					is_display: true,
				},
				{
					id: 'catalog_group',
					name: 'Catalog Group',
					options: [],
					priority: 3,
					required: true,
					type: 'select',
					value: '',
					is_quick_add: true,
					is_display: true,
				},
				{
					id: 'email',
					name: 'Email ID',
					type: 'email',
					value: '',
					priority: 5,
					required: false,
					is_editable: true,
					is_display: false,
					is_quick_add: false,
					check_duplicate: true,
				},
				{
					id: 'phone',
					name: 'Phone',
					type: 'phone_e164',
					value: '',
					priority: 6,
					required: false,
					is_editable: true,
					is_display: false,
					is_quick_add: false,
					check_duplicate: true,
				},
				{
					id: 'type_of_customer',
					name: 'Customer Type',
					type: 'select',
					value: '',
					options: [
						{
							label: 'Designer',
							value: 'Designer',
						},
						{
							label: 'Retail',
							value: 'Retail',
						},
						{
							label: 'Wholesale',
							value: 'Wholesale',
						},
					],
					priority: 4,
					required: false,
					is_editable: false,
					is_display: false,
					is_quick_add: false,
					attribute_class: null,
					dynamic_attr_config: null,
				},
			],
			key: 'basic_details',
			name: 'Basic Details',
			priority: 0,
			is_hidden: false,
			is_quick_add: true,
			is_display: true,
		},
		{
			attachments: [{ file_id: '', id: '', status: '' }],
			custom_attributes: [],
			key: 'other_details',
			name: 'Other Details',
			priority: 1,
			is_hidden: false,
			is_display: false,
			is_attachment_display: true,
			is_quick_add: false,
		},
		{
			contacts: [
				{
					attributes: [
						{
							id: 'first_name',
							name: 'First Namee',
							priority: 1,
							required: true,
							type: 'text',
							value: '',
							is_display: true,
							is_quick_add: true,
						},
						{
							id: 'last_name',
							name: 'Last Name',
							priority: 1,
							required: true,
							type: 'text',
							value: '',
							is_display: true,
							is_quick_add: true,
						},
						{
							id: 'country_code',
							name: 'Country Code',
							priority: 3,
							required: false,
							type: 'text',
							value: '',
							is_display: true,
							is_quick_add: true,
						},
						{
							id: 'phone',
							name: 'Phone number',
							priority: 4,
							required: true,
							type: 'number',
							value: '',
							is_display: true,
							is_quick_add: true,
						},
						{
							id: 'email',
							name: 'Email',
							priority: 5,
							required: false,
							type: 'email',
							value: '',
							is_display: false,
							is_quick_add: false,
						},
						{
							id: 'designation',
							name: 'Designation',
							priority: 4,
							required: false,
							type: 'text',
							value: '',
							is_display: true,
							is_quick_add: false,
						},
					],
				},
			],
			required: false,
			key: 'contacts',
			name: 'Contact',
			priority: 2,
			is_hidden: false,
			is_quick_add: true,
			is_display: true,
		},
		{
			addresses: [
				{
					attributes: [
						{
							id: 'first_name',
							name: 'First Name',
							priority: 0,
							required: true,
							type: 'text',
							value: '',
							is_display: true,
							is_quick_add: true,
						},
						{
							id: 'last_name',
							name: 'Last Name',
							priority: 1,
							required: false,
							type: 'text',
							value: '',
							is_display: true,
							is_quick_add: true,
						},
						{
							id: 'country_code',
							name: 'Country Code',
							priority: 2,
							required: false,
							type: 'text',
							value: '',
							is_display: true,
							is_quick_add: true,
						},
						{
							id: 'phone',
							name: 'Phone number',
							priority: 3,
							required: false,
							type: 'number',
							value: '',
							is_display: true,
							is_quick_add: true,
						},
						{
							id: 'email',
							name: 'Email ID',
							priority: 4,
							required: false,
							type: 'email',
							value: '',
							is_display: true,
							is_quick_add: true,
						},
						{
							disabled: false,
							id: 'country',
							name: 'Country',
							options: [{ label: 'United States of America', value: 'usa' }],
							priority: 5,
							required: false,
							type: 'select',
							value: 'USA',
							is_display: true,
							is_quick_add: true,
						},
						{
							id: 'street_address',
							is_taking_full_row: true,
							name: 'Street Address',
							priority: 6,
							required: true,
							type: 'text',
							value: '',
							is_display: true,
							is_quick_add: true,
						},
						{
							id: 'address_line_2',
							is_taking_full_row: true,
							name: 'Address Line 2',
							priority: 7,
							required: false,
							type: 'text',
							value: '',
							is_display: true,
							is_quick_add: true,
						},
						{
							id: 'city',
							name: 'City',
							priority: 8,
							required: true,
							type: 'text',
							value: '',
							is_display: true,
							is_quick_add: true,
						},
						{
							disabled: false,
							id: 'state',
							name: 'State / Region',
							priority: 9,
							required: true,
							type: 'text',
							value: '',
							is_display: true,
							is_quick_add: true,
						},
						{
							id: 'pincode',
							name: 'Zip Code',
							priority: 10,
							required: true,
							type: 'number',
							value: '',
							is_display: true,
							is_quick_add: true,
						},
						{
							id: 'type',
							name: 'Address Type',
							priority: 11,
							required: true,
							type: 'text',
							value: '',
							is_display: true,
							is_quick_add: true,
						},
					],
				},
			],
			key: 'addresses',
			name: 'Addresses',
			required: false,
			priority: 3,
			is_quick_add: true,
			is_display: true,
			required_exclusion_type: ['billing', 'shipping'],
			is_display_exclusion_type: [],
		},
		{
			attributes: [
				{
					id: 'payment_mode',
					name: 'Mode of Payment',
					options: [
						{ label: 'Cash', value: 'cash' },
						{ label: 'Debit Card', value: 'debitcard' },
						{ label: 'Wire Transfers', value: 'wiretransfer' },
						{ label: 'Demand Drafts', value: 'dd' },
					],
					priority: 0,
					required: false,
					type: 'select',
					value: 'debitcard, wiretransfer',
					is_quick_add: false,
					is_display: true,
				},
				{
					id: 'payment_terms',
					name: 'Payment Terms',
					options: [
						{ label: 'Net 30', value: 'net30' },
						{ label: 'Cash in advance', value: 'cash_in_advance' },
						{ label: 'Letter in advance', value: 'letter_in_advance' },
						{ label: 'dfv', value: 'sfsdfsf' },
					],
					priority: 1,
					required: false,
					type: 'select',
					value: '',
					is_quick_add: true,
					is_display: true,
				},
				{
					id: 'freight_terms',
					name: 'Freight Terms',
					options: [
						{
							label: 'FEDEX ACCOUNT# 658399233',
							value: 'fedex_account#_658399233',
						},
						{
							label: '***UPS 3RD PARTY 670455',
							value: '***ups_3rd_party_670455',
						},
						{
							label: '**99 FFA**',
							value: '**99_ffa**',
						},
						{
							label: '**100 FFA**',
							value: '**100_ffa**',
						},
						{
							label: '*SHIP UPS 3RD PARTY #3057E5 UNDER $500*',
							value: '*ship_ups_3rd_party_#3057e5_under_$500*',
						},
						{
							label: '**FFA***',
							value: '**ffa***',
						},
						{
							label: '****UPS ACCT 69Y65A****',
							value: '****ups_acct_69y65a****',
						},
						{
							label: '*PLEASE USE FEDEX LABEL PROVIDED*',
							value: '*please_use_fedex_label_provided*',
						},
						{
							label: '**FEDEX 3RD PARTY 3486-7292-4',
							value: '**fedex_3rd_party_3486-7292-4',
						},
						{
							label: '**UPS 3RD PARTY 23A79F*',
							value: '**ups_3rd_party_23a79f*',
						},
						{
							label: '**FEDEX 3RD PARTY # 214586223**',
							value: '**fedex_3rd_party_#_214586223**',
						},
						{
							label: '*UPS 3RD PARTY**',
							value: '*ups_3rd_party**',
						},
						{
							label: '***FFA $99***',
							value: '***ffa_$99***',
						},
						{
							label: 'FFA ALL- US PRICING',
							value: 'ffa_all-_us_pricing',
						},
						{
							label: '**UPS 3RD PARTY W4E170**NO DROP SHIP FEE',
							value: '**ups_3rd_party_w4e170**no_drop_ship_fee',
						},
						{
							label: '***UPS 019RE4***',
							value: '***ups_019re4***',
						},
						{
							label: '*FFA  ALL*',
							value: '*ffa__all*',
						},
						{
							label: 'US Standard - Lighting 1',
							value: 'us_standard_-_lighting_1',
						},
						{
							label: 'FFA/100',
							value: 'ffa/100',
						},
						{
							label: '**FFA  ALL ORDERS**',
							value: '**ffa__all_orders**',
						},
						{
							label: '** SHIP UPS   3Y319W** ORDERS UND $500',
							value: '**_ship_ups___3y319w**_orders_und_$500',
						},
						{
							label: '**ship using their account**',
							value: '**ship_using_their_account**',
						},
						{
							label: '**FFA OVER 100**',
							value: '**ffa_over_100**',
						},
						{
							label: '**FEDEX 3RD PARTY # 876058081**',
							value: '**fedex_3rd_party_#_876058081**',
						},
						{
							label: '**FFA 100**',
							value: '**ffa_100**',
						},
						{
							label: '*NO DROP SHIP FEE****FEDEX ACCT # 620409995***',
							value: '*no_drop_ship_fee****fedex_acct_#_620409995***',
						},
						{
							label: 'US Standard No Fees - Lighting 1',
							value: 'us_standard_no_fees_-_lighting_1',
						},
						{
							label: '**99  FFA**',
							value: '**99__ffa**',
						},
						{
							label: '**UPS 3RD PARTY 946586*',
							value: '**ups_3rd_party_946586*',
						},
						{
							label: '***SHIP UPS ACCOUNT # 6Y4915***',
							value: '***ship_ups_account_#_6y4915***',
						},
						{
							label: 'UPS 3RD  PARTY ACCOUNT# T3301T',
							value: 'ups_3rd__party_account#_t3301t',
						},
						{
							label: 'Canada Standard',
							value: 'canada_standard',
						},
						{
							label: '***FFA ON ALL***',
							value: '***ffa_on_all***',
						},
						{
							label: '**UPS 3RD PARTY 4F4030**',
							value: '**ups_3rd_party_4f4030**',
						},
						{
							label: '**FFA/TUESDAY**UPS 3RD PARTY#6A7E32*',
							value: '**ffa/tuesday**ups_3rd_party#6a7e32*',
						},
						{
							label: '**FFA 99 EVERYDAY**',
							value: '**ffa_99_everyday**',
						},
						{
							label: '***FFA***',
							value: '***ffa***',
						},
						{
							label: '**SHIP UPS E1R828**',
							value: '**ship_ups_e1r828**',
						},
						{
							label: '**UPS 3RD PARTY 866Y1W**',
							value: '**ups_3rd_party_866y1w**',
						},
						{
							label: 'US Standard',
							value: 'us_standard',
						},
						{
							label: '*FFA*',
							value: '*ffa*',
						},
						{
							label: '***99 FFA***',
							value: '***99_ffa***',
						},
						{
							label: '**ups acct 48X232*******  99 FFA',
							value: '**ups_acct_48x232*******__99_ffa',
						},
						{
							label: '***third party billing************',
							value: '***third_party_billing************',
						},
						{
							label: '**FFA ALL ************',
							value: '**ffa_all_************',
						},
						{
							label: '*FEDEX 3RD PARTY ACCOUNT#251150427',
							value: '*fedex_3rd_party_account#251150427',
						},
						{
							label: '***FFA OVER 100***',
							value: '***ffa_over_100***',
						},
						{
							label: '***FFA+100**',
							value: '***ffa+100**',
						},
						{
							label: '*******USE UPS A952Y1*******',
							value: '*******use_ups_a952y1*******',
						},
						{
							label: '***FFA/100***',
							value: '***ffa/100***',
						},
						{
							label: '**UPS 3RD PARTY E6Y320**',
							value: '**ups_3rd_party_e6y320**',
						},
						{
							label: '*UPS 3RD PARTY ACCT # 8313V2*',
							value: '*ups_3rd_party_acct_#_8313v2*',
						},
						{
							label: 'US Standard No Fees',
							value: 'us_standard_no_fees',
						},
						{
							label: '***FEDEX 3RD PARTY ACCOUNT***',
							value: '***fedex_3rd_party_account***',
						},
						{
							label: 'THIRD PARTY',
							value: 'third_party',
						},
						{
							label: 'FEDEX 3RD PARTY 149085114**',
							value: 'fedex_3rd_party_149085114**',
						},
						{
							label: 'FFA',
							value: 'ffa',
						},
						{
							label: '***PLEASE USE UPS ACCT #535024***',
							value: '***please_use_ups_acct_#535024***',
						},
						{
							label: '99 FFA',
							value: '99_ffa',
						},
					],
					priority: 2,
					required: true,
					type: 'select',
					value: 'fedex_account#_658399233',
					is_quick_add: true,
					is_display: true,
				},
				{
					id: 'shipping_method',
					name: 'Shipment Method',
					options: [
						{
							label: 'FedEx',
							value: 'fedex',
						},
						{
							label: 'UPS',
							value: 'ups',
						},
						{
							label: 'USPS',
							value: 'usps',
						},
						{
							label: 'DHL',
							value: 'dhl',
						},
						{
							label: 'Estes',
							value: 'estes',
						},
					],
					priority: 3,
					required: false,
					type: 'select',
					is_quick_add: true,
					is_display: true,
				},
			],
			key: 'preferences',
			name: 'Preferences',
			priority: 4,
			is_hidden: false,
			is_display: false,
			is_quick_add: true,
		},
		{
			key: 'tax_preferences',
			name: 'Tax Preferences',
			priority: 3,
			required: false,
			attributes: [
				{
					id: 'is_taxable',
					name: 'Is Taxable',
					type: 'radio',
					value: false,
					priority: 0,
					options: [
						{
							label: 'Taxable',
							value: true,
						},
						{
							label: 'Non-taxable',
							value: false,
						},
					],
					required: false,
					is_editable: true,
					is_display: false,
				},
				{
					id: 'tax_rate',
					name: 'Tax rate',
					type: 'percentage',
					value: 8.25,
					priority: 1,
					required: false,
					disabled: false,
					is_editable: true,
					is_display: false,
				},
			],
			is_display: false,
			is_quick_add: false,
		},
		{
			key: 'payment_methods',
			name: 'Payment Methods',
			priority: 3,
			required: false,
			attributes: [
				{
					id: 'customer_id',
					name: '',
					label: '',
					type: 'text',
					value: '',
					priority: 0,
					required: false,
					is_display: true,
					is_quick_add: false,
				},
				{
					id: 'payment_method_ids',
					name: '',
					label: '',
					type: 'multi_select_array',
					value: [],
					priority: 0,
					required: false,
					is_display: true,
					is_quick_add: false,
				},
				{
					id: 'default_payment_method_id',
					label: '',
					type: 'text',
					value: '',
					priority: 0,
					required: false,
					is_display: true,
					is_quick_add: false,
				},
			],
			saved_payment_methods: {},
			is_display: false,
			is_quick_add: false,
		},
	],
};
